# Generated by Django 4.0.4 on 2022-05-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_professor_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
