# Generated by Django 4.0.4 on 2022-05-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_professor_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='userId',
            new_name='user',
        ),
    ]
