# Generated by Django 4.0.4 on 2022-05-31 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_student_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
    ]
