# Generated by Django 4.0.4 on 2022-06-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_coursereview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecourseresource',
            name='file_resource',
            field=models.FileField(upload_to='resources/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
