# Generated by Django 4.0.4 on 2022-06-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_filecourseresource_file_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecourseresource',
            name='file_name',
            field=models.CharField(default='name', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filecourseresource',
            name='file_resource',
            field=models.FileField(upload_to='resources'),
        ),
    ]
