# Generated by Django 4.0.4 on 2022-06-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_filecourseresource_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecourseresource',
            name='file_name',
            field=models.CharField(max_length=100),
        ),
    ]
