# Generated by Django 4.0.4 on 2022-06-09 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_event_author_alter_announcements_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
