# Generated by Django 4.0.4 on 2022-06-11 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_event_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='lectureHall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.lecturehall'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(),
        ),
    ]
