# Generated by Django 4.0.4 on 2022-06-28 21:04

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_course_description_alter_course_lecturehall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecourseresource',
            name='file_resource',
            field=models.FileField(upload_to='resources', validators=[main.validators.validate_file_extension]),
        ),
    ]
