# Generated by Django 4.0.4 on 2022-06-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_filecourseresource_file_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecourseresource',
            name='file_resource',
            field=models.FileField(upload_to='resources'),
        ),
    ]
